Repository droidknights/DroidKnightsApp, pull requests merged in 2025-05, with the labels that each got.

#342 Workspace/run configuration
  .run/androidApp.run.xml
  .run/backend.run.xml
  .run/desktop.run.xml
  .run/iosApp.run.xml
  .run/web.run.xml
  README.md
  backend/.gitignore
  backend/build.gradle.kts
  backend/src/main/kotlin/com/droidknights/app/Application.kt
  backend/src/main/resources/logback.xml
  docs/image.png
  settings.gradle.kts
Labels: documentation, enhancement, 2025

#350 [jvm-cd] 데스크탑 앱 PR/디벨롭 머지시에 빌드 결과 저장/PR 댓글 다는 기능 추가
  .github/workflows/jvm-desktop-build.yml
  .github/workflows/jvm-desktop-comment.yml
Labels: 2025

#351 [init-theme] 테마 초기화
  composeApp/src/androidMain/kotlin/com/droidknights/app/MainActivity.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Scaffold.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Color.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Typography.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainScreen.kt
Labels: 2025

#353 [bump-dependencies-250507] 의존성 업데이트
  README.md
  gradle/libs.versions.toml
Labels: 2025

#352 [remove-material3] material3 의존성 제거
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Button.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Icon.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Scaffold.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Surface.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Text.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Color.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/ContentColor.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/HomeScreen.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainScreen.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainNavHost.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/navigation/SettingNavigation.kt
  kotlin-js-store/yarn.lock
Labels: 2025

#354 [main-bottom-bar] MainBottomBar 추가
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/BookmarkScreen.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/navigation/BookmarkNavigation.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/navigation/HomeNavigation.kt
  feature/main/src/commonMain/composeResources/drawable/ic_bookmark.xml
  feature/main/src/commonMain/composeResources/drawable/ic_home.xml
  feature/main/src/commonMain/composeResources/drawable/ic_setting.xml
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainNavigator.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainScreen.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainTab.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainBottomBar.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainNavHost.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionScreen.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/navigation/SessionNavigation.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/SettingScreen.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/navigation/SettingNavigation.kt
Labels: 2025

#356 [desktop-web] 데스크탑 웹 (넓은 가로)에서 프로젝트 소개 영역과 앱 동작 확인 영역을 나눈다
  composeApp/src/commonMain/composeResources/drawable/compose-multiplatform.xml
  composeApp/src/commonMain/composeResources/drawable/ic_battery.xml
  composeApp/src/commonMain/composeResources/drawable/ic_github.xml
  composeApp/src/commonMain/composeResources/drawable/ic_signal.xml
  composeApp/src/commonMain/composeResources/drawable/ic_wifi.xml
  composeApp/src/commonMain/composeResources/drawable/img_front_camera.png
  composeApp/src/wasmJsMain/kotlin/com/droidknights/app/ProjectDescription.kt
  composeApp/src/wasmJsMain/kotlin/com/droidknights/app/main.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainBottomBar.kt
Labels: 2025

#357 [2025][CMP] Compose Multiplatform에 detekt 적용
  .github/workflows/detekt.yml
  README.md
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/com/droidknights/app/convention/KotlinMultiPlatformConventionPlugin.kt
  build-logic/src/main/kotlin/com/droidknights/app/primitive/DetektPlugin.kt
  build.gradle.kts
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/com/droidknights/app/MainActivity.kt
  composeApp/src/commonMain/kotlin/com/droidknights/app/App.kt
  composeApp/src/desktopMain/kotlin/com/droidknights/app/main.kt
  composeApp/src/iosMain/kotlin/com/droidknights/app/MainViewController.kt
  composeApp/src/wasmJsMain/kotlin/com/droidknights/app/ProjectDescription.kt
  composeApp/src/wasmJsMain/kotlin/com/droidknights/app/main.kt
  config/detekt/detekt.yml
  core/designsystem/build.gradle.kts
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Button.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Icon.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Surface.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Text.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Color.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/ContentColor.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Typography.kt
  core/navigation/build.gradle.kts
  feature/bookmark/build.gradle.kts
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/BookmarkScreen.kt
  feature/contributor/build.gradle.kts
  feature/contributor/src/commonMain/kotlin/com/droidknights/app/feature/contributor/ContributorScreen.kt
  feature/home/build.gradle.kts
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainScreen.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainTab.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainBottomBar.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainNavHost.kt
  feature/session/build.gradle.kts
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionDetailScreen.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionScreen.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/navigation/SessionNavigation.kt
  feature/setting/build.gradle.kts
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/SettingScreen.kt
  gradle/libs.versions.toml
  hooks/pre-commit
  scripts/install-hooks.sh
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Constants.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Room.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Session.kt
  shared/src/desktopMain/kotlin/com/droidknights/app/shared/Tag.kt
  shared/src/wasmJsMain/kotlin/com/droidknights/app/shared/Tag.kt
Labels: 2025 / CMP

#360 [2025][CMP] iOS 앱 아이콘 및 Accent Color 설정
  iosApp/iosApp.xcodeproj/project.pbxproj
  iosApp/iosApp/Assets.xcassets/AccentColor.colorset/Contents.json
  iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png
  iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/droidknights_icon_1024.png
Labels: 2025 / CMP

#359 [2025][CMP] HomeScreen 구현
  build-logic/src/main/kotlin/com/droidknights/app/convention/ComposeMultiPlatformConventionPlugin.kt
  config/detekt/detekt.yml
  core/ui/shader/build.gradle.kts
  core/ui/shader/src/androidMain/kotlin/com/droidknights/app/core/shader/RuntimeEffect.android.kt
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/RuntimeEffect.kt
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/Shader.kt
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/BottomUpGlowBackground.kt
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/ShaderBackground.kt
  core/ui/shader/src/nonAndroidMain/kotlin/com/droidknights/app/core/shader/RuntimeEffect.nonAndroid.kt
  feature/home/build.gradle.kts
  feature/home/src/commonMain/composeResources/drawable/background_home_map_card.png
  feature/home/src/commonMain/composeResources/drawable/background_home_sponsor_card.png
  feature/home/src/commonMain/composeResources/drawable/ic_location.xml
  feature/home/src/commonMain/composeResources/values/strings.xml
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeContributorCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeMapCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSessionCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSponsorCard.kt
  settings.gradle.kts
Labels: 2025 / CMP

#364 (DEP) #361 디펜던시 최신화
  build-logic/src/main/kotlin/com/droidknights/app/KotlinAndroid.kt
  build-logic/src/main/kotlin/droidknights.kotlin.library.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: dependency, 2025

#365 (DEP)[#339] 빌드 로직 리펙
  app/build.gradle.kts
  build-logic/README.md
  build-logic/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/droidknights/app/AppNameExtension.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/ComposeAndroid.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/CoroutineAndroid.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/Extension.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/HiltAndroid.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/HiltKotlin.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/KotestAndroid.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/KotestKotlin.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/KotlinAndroid.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/Roborazzi.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/VerifyDetekt.kt
  build-logic/convention/src/main/kotlin/droidknights.android.application.gradle.kts
  build-logic/convention/src/main/kotlin/droidknights.android.compose.gradle.kts
  build-logic/convention/src/main/kotlin/droidknights.android.feature.gradle.kts
  build-logic/convention/src/main/kotlin/droidknights.android.library.gradle.kts
  build-logic/convention/src/main/kotlin/droidknights.kotlin.library.gradle.kts
  build-logic/convention/src/main/kotlin/droidknights.verify.detekt.gradle.kts
  build-logic/gradle.properties
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/com/droidknights/app/ComposeAndroid.kt
  core/data-api/build.gradle.kts
  core/data/build.gradle.kts
  core/datastore/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/domain/build.gradle.kts
  core/model/build.gradle.kts
  core/navigation/build.gradle.kts
  core/testing/build.gradle.kts
  core/ui-test-hilt-manifest/build.gradle.kts
  core/ui/build.gradle.kts
  feature/bookmark/build.gradle.kts
  feature/contributor/build.gradle.kts
  feature/home/build.gradle.kts
  feature/main/build.gradle.kts
  feature/session/build.gradle.kts
  feature/setting/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  widget/build.gradle.kts
Labels: dependency, 2025

#372 (FEAT)[#371] 내부용 BuildConfig 별도 모듈 추가
  app-config/app-config-api/build.gradle.kts
  app-config/app-config-api/src/main/AndroidManifest.xml
  app-config/app-config-api/src/main/java/com/droidknights/app/config/api/DroidknightsBuildConfig.kt
  app-config/app-config/build.gradle.kts
  app-config/app-config/src/main/AndroidManifest.xml
  app-config/app-config/src/main/java/com/droidknights/app/config/DroidknightsBuildConfigImpl.kt
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/droidknights/app/KotlinAndroid.kt
  core/domain/src/main/java/com/droidknights/app/core/domain/.gitkeep
  core/network/network/build.gradle.kts
  core/network/network/src/main/java/com/droidknights/app/core/network/di/NetworkModule.kt
  settings.gradle.kts
Labels: enhancement, 2025

#376 (FIX)[#375] 순한참조 오류 수정
  app-config/app-config/src/main/java/com/droidknights/app/config/di/BuildConfigModule.kt
  build-logic/convention/src/main/kotlin/KotlinLibraryConventionPlugin.kt
  build-logic/convention/src/main/kotlin/KotlinLibrarySerializationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/com/droidknights/app/DependencyExtensions.kt
  settings.gradle.kts
Labels: bug, 2025

#377 (REF)[#362] data 모듈 경로 수정
  build-logic/convention/src/main/kotlin/droidknights.android.feature.gradle.kts
  core/data/data-api/build.gradle.kts
  core/data/data-api/src/main/AndroidManifest.xml
  core/data/data-api/src/main/java/com/droidknights/app/core/data/repository/api/ContributorRepository.kt
  core/data/data-api/src/main/java/com/droidknights/app/core/data/repository/api/SessionRepository.kt
  core/data/data-api/src/main/java/com/droidknights/app/core/data/repository/api/SettingsRepository.kt
  core/data/data-api/src/main/java/com/droidknights/app/core/data/repository/api/SponsorRepository.kt
  core/data/data/build.gradle.kts
  core/data/data/src/main/AndroidManifest.xml
  core/data/data/src/main/assets/contributors.json
  core/data/data/src/main/assets/sessions.json
  core/data/data/src/main/assets/sponsors.json
  core/data/data/src/main/java/com/droidknights/app/core/data/api/GithubApi.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/GithubRawApi.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/fake/AssetsGithubRawApi.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/model/ContributionYearResponse.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/model/ContributorResponse.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/model/RoomResponse.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/model/SessionResponse.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/model/SpeakerResponse.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/api/model/SponsorResponse.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/di/ApiModule.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/di/DataModule.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/mapper/ContributorMapper.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/mapper/ContributorWithYearsMapper.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/mapper/SessionMapper.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/mapper/SponsorMapper.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/repository/DefaultContributorRepository.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/repository/DefaultSessionRepository.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/repository/DefaultSettingsRepository.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/repository/DefaultSponsorRepository.kt
  core/data/data/src/test/java/com/droidknights/app/core/data/api/fake/FakeGithubApi.kt
  core/data/data/src/test/java/com/droidknights/app/core/data/api/fake/FakeGithubRawApi.kt
  core/data/data/src/test/java/com/droidknights/app/core/data/datastore/fake/FakeSessionPreferencesDataSource.kt
  core/data/data/src/test/java/com/droidknights/app/core/data/repository/DefaultContributorRepositoryTest.kt
  core/data/data/src/test/java/com/droidknights/app/core/data/repository/DefaultSessionRepositoryTest.kt
  core/data/data/src/test/java/com/droidknights/app/core/data/repository/DefaultSponsorRepositoryTest.kt
  core/domain/build.gradle.kts
  feature/main/build.gradle.kts
  settings.gradle.kts
Labels: 2025

#378 (FEAT)[#368] Junit5 수정
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/droidknights/app/MockTest.kt
  build-logic/convention/src/main/kotlin/droidknights.android.library.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement, 2025

#379 (FEAT)[#362] Settings 데이터 분리
  build-logic/convention/src/main/kotlin/droidknights.android.feature.gradle.kts
  core/data/data-settings-api/build.gradle.kts
  core/data/data-settings-api/src/main/AndroidManifest.xml
  core/data/data-settings-api/src/main/java/com/droidknights/app/core/data/settings/api/SettingsRepository.kt
  core/data/data-settings/build.gradle.kts
  core/data/data-settings/src/main/AndroidManifest.xml
  core/data/data-settings/src/main/java/com/droidknights/app/core/data/settings/SettingsRepositoryImpl.kt
  core/data/data-settings/src/main/java/com/droidknights/app/core/data/settings/di/SettingsDataModule.kt
  core/data/data-settings/src/test/java/com/droidknights/app/core/data/settings/SettingsRepositoryImplTest.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/di/DataModule.kt
  core/domain/domain/build.gradle.kts
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/BookmarkSessionUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/DeleteBookmarkedSessionUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetBookmarkedSessionIdsUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetBookmarkedSessionsUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetContributorsUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetSessionUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetSessionsUseCase.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetSponsorsUseCase.kt
  core/domain/domain/src/test/java/com/droidknights/app/core/domain/usecase/FakeContributorRepository.kt
  core/domain/domain/src/test/java/com/droidknights/app/core/domain/usecase/FakeSessionRepository.kt
  core/domain/domain/src/test/java/com/droidknights/app/core/domain/usecase/GetBookmarkedSessionsUseCaseTest.kt
  core/domain/domain/src/test/java/com/droidknights/app/core/domain/usecase/GetContributorsUseCaseTest.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/droidknights/app/feature/main/MainViewModel.kt
  settings.gradle.kts
  widget/build.gradle.kts
Labels: enhancement, 2025

#383 (REF)[#382] Sponsor data/doamin 모듈 분리
  app-config/app-config-api/src/main/java/com/droidknights/app/config/api/DroidknightsBuildConfig.kt
  app-config/app-config/src/main/java/com/droidknights/app/config/DroidknightsBuildConfigImpl.kt
  core/data/data-sponsor-api/build.gradle.kts
  core/data/data-sponsor-api/src/main/AndroidManifest.xml
  core/data/data-sponsor-api/src/main/java/com/droidknights/app/core/data/sponsor/api/SponsorRepository.kt
  core/data/data-sponsor/build.gradle.kts
  core/data/data-sponsor/src/main/AndroidManifest.xml
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/SponsorRepositoryImpl.kt
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/api/SponsorApi.kt
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/api/model/SponsorResponse.kt
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/di/ApiModule.kt
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/di/SponsorDataModule.kt
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/mapper/SponsorMapper.kt
  core/data/data-sponsor/src/test/assets/sponsors.json
  core/data/data-sponsor/src/test/java/com/droidknights/app/core/data/sponsor/SponsorRepositoryImplTest.kt
  core/data/data-sponsor/src/test/java/com/droidknights/app/core/data/sponsor/fake/FakeDroidknightsBuildConfig.kt
  core/data/data-sponsor/src/test/java/com/droidknights/app/core/data/sponsor/fake/FakeSponsorApi.kt
  core/data/data/src/main/java/com/droidknights/app/core/data/di/DataModule.kt
  core/datastore/src/main/java/com/droidknights/app/core/datastore/datasource/SessionPreferencesDataSource.kt
  core/datastore/src/main/java/com/droidknights/app/core/datastore/datasource/di/DatastoreModule.kt
  core/domain/domain-sponsor-api/build.gradle.kts
  core/domain/domain-sponsor-api/src/main/java/com/droidknights/app/core/domain/sponsor/api/GetSponsorsUseCase.kt
  core/domain/domain-sponsor/build.gradle.kts
  core/domain/domain-sponsor/src/main/java/com/droidknights/app/core/domain/sponsor/GetSponsorsUseCaseImpl.kt
  core/domain/domain-sponsor/src/main/java/com/droidknights/app/core/domain/sponsor/di/SponsorDomainModule.kt
  core/domain/domain-sponsor/src/test/java/com/droidknights/app/core/domain/sponsor/GetSponsorsUseCaseImplTest.kt
  core/domain/domain/src/main/java/com/droidknights/app/core/domain/usecase/GetSponsorsUseCase.kt
  core/model/src/main/java/com/droidknights/app/core/model/Sponsor.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/droidknights/app/feature/home/HomeViewModel.kt
  feature/home/src/test/java/com/droidknights/app/feature/home/HomeViewModelTest.kt
  settings.gradle.kts
Labels: enhancement, 2025

#394 (BUG)[#393] 2025 앱 CI 테스트 실패 문제를 해결
  .github/workflows/android-pull-request-ci.yml
  core/data/data-session/src/test/java/com/droidknights/app/core/data/session/fake/FakeSessionPreferencesDataSource.kt
  core/data/data-settings/src/test/java/com/droidknights/app/core/data/settings/SettingsRepositoryImplTest.kt
  core/network/network/src/test/java/com/droidknights/app/core/network/MockDroidknightsService.kt
  feature/contributor/src/androidTest/java/com/droidknights/app/feature/contributor/ContributorScreenTest.kt
  feature/home/src/test/java/com/droidknights/app/feature/home/HomeViewModelTest.kt
Labels: bug, 2025

#396 (REF)[#395] Domain impl 생성자 명칭 수정
  core/domain/domain-session/src/main/java/com/droidknights/app/core/domain/session/usecase/GetBookmarkedSessionsUseCaseImpl.kt
Labels: enhancement, 2025

#399 [2025][CMP] Koin을 이용한 DI 구현
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/com/droidknights/app/MainActivity.kt
  composeApp/src/commonMain/kotlin/com/droidknights/app/App.kt
  composeApp/src/commonMain/kotlin/com/droidknights/app/AppViewModel.kt
  composeApp/src/commonMain/kotlin/com/droidknights/app/model/AppUiState.kt
  composeApp/src/wasmJsMain/kotlin/com/droidknights/app/ProjectDescription.kt
  composeApp/src/wasmJsMain/kotlin/com/droidknights/app/main.kt
  core/data/data-setting-api/build.gradle.kts
  core/data/data-setting-api/src/commonMain/kotlin/com/droidknights/app/core/data/setting/api/SettingRepository.kt
  core/data/data-setting/build.gradle.kts
  core/data/data-setting/src/commonMain/kotlin/com/droidknights/app/core/data/setting/SettingRepositoryImpl.kt
  core/data/data-setting/src/commonMain/kotlin/com/droidknights/app/core/data/setting/di/Module.kt
  feature/main/build.gradle.kts
  feature/main/src/commonMain/composeResources/drawable/ic_battery.xml
  feature/main/src/commonMain/composeResources/drawable/ic_github.xml
  feature/main/src/commonMain/composeResources/drawable/ic_signal.xml
  feature/main/src/commonMain/composeResources/drawable/ic_wifi.xml
  feature/main/src/commonMain/composeResources/drawable/img_front_camera.png
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainScreen.kt
  feature/main/src/nonWasmJsMain/kotlin/com/droidknights/app/feature/main/MainScreen.nonWasmJs.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/MainScreen.wasmJs.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/DeviceFrame.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/ProjectDescription.kt
  feature/setting/build.gradle.kts
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/SettingScreen.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/SettingViewModel.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/components/SettingDarkThemeCard.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/components/SettingOpenSourceCard.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/di/Module.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/model/SettingUiState.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2025 / CMP

#401 [REF] 홈 카드 수정 및 디자인 최신화
  feature/home/build.gradle.kts
  feature/home/src/commonMain/composeResources/drawable/background_home_session_card.png
  feature/home/src/commonMain/composeResources/drawable/sponsor_logo_jetbrains.xml
  feature/home/src/commonMain/composeResources/values/strings.xml
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSessionCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSponsorCard.kt
Labels: 2025 / CMP

#403 [2025][CMP] session fake data + 모듈 구현 + ui 연결
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/com/droidknights/app/App.kt
  core/data/data-session-api/build.gradle.kts
  core/data/data-session-api/src/commonMain/kotlin/com/droidknights/app/core/data/session/api/SessionRepository.kt
  core/data/data-session/build.gradle.kts
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/SessionRepositoryImpl.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/di/Module.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/mapper/SessionMapper.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/model/RoomResponse.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/model/SessionResponse.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/model/SpeakerResponse.kt
  core/domain/domain-session-api/build.gradle.kts
  core/domain/domain-session-api/src/commonMain/kotlin/com/droidknights/app/core/domain/session/api/usecase/BookmarkSessionUseCase.kt
  core/domain/domain-session-api/src/commonMain/kotlin/com/droidknights/app/core/domain/session/api/usecase/DeleteBookmarkedSessionUseCase.kt
  core/domain/domain-session-api/src/commonMain/kotlin/com/droidknights/app/core/domain/session/api/usecase/GetBookmarkedSessionIdsUseCase.kt
  core/domain/domain-session-api/src/commonMain/kotlin/com/droidknights/app/core/domain/session/api/usecase/GetBookmarkedSessionsUseCase.kt
  core/domain/domain-session-api/src/commonMain/kotlin/com/droidknights/app/core/domain/session/api/usecase/GetSessionUseCase.kt
  core/domain/domain-session-api/src/commonMain/kotlin/com/droidknights/app/core/domain/session/api/usecase/GetSessionsUseCase.kt
  core/domain/domain-session/build.gradle.kts
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/di/Module.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/BookmarkSessionUseCaseImpl.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/DeleteBookmarkedSessionUseCaseImpl.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/GetBookmarkedSessionIdsUseCaseImpl.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/GetBookmarkedSessionsUseCaseImpl.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/GetSessionUseCaseImpl.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/GetSessionsUseCaseImpl.kt
  core/model/model-session/build.gradle.kts
  core/model/model-session/src/commonMain/kotlin/com/droidknights/app/core/model/session/Room.kt
  core/model/model-session/src/commonMain/kotlin/com/droidknights/app/core/model/session/Session.kt
  core/model/model-session/src/commonMain/kotlin/com/droidknights/app/core/model/session/Speaker.kt
  core/model/model-session/src/commonMain/kotlin/com/droidknights/app/core/model/session/Tag.kt
  feature/session/build.gradle.kts
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionDetailScreen.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionDetailViewModel.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionScreen.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/SessionViewModel.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/di/Module.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/model/SessionDetailUiState.kt
  feature/session/src/commonMain/kotlin/com/droidknights/app/feature/session/model/SessionUiState.kt
  feature/setting/build.gradle.kts
  settings.gradle.kts
  shared/src/androidMain/kotlin/com/droidknights/app/shared/Tag.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Room.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Session.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Speaker.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Sponsor.kt
  shared/src/commonMain/kotlin/com/droidknights/app/shared/Tag.kt
  shared/src/desktopMain/kotlin/com/droidknights/app/shared/Tag.kt
  shared/src/iosMain/kotlin/com/droidknights/app/shared/Tag.kt
  shared/src/wasmJsMain/kotlin/com/droidknights/app/shared/Tag.kt
Labels: 2025 / CMP

#408 [Feature] 멀티플랫폼 웹에 프로젝트 컨트리뷰션 소개 내용을 추가
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Button.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Text.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Typography.kt
  feature/main/build.gradle.kts
  feature/main/src/commonMain/composeResources/drawable/ic_branch.xml
  feature/main/src/commonMain/composeResources/drawable/web_logo.xml
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/MainScreen.wasmJs.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/AppBar.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/Contributors.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/DeviceFrame.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/ProjectBranchButtons.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/ProjectDescription.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/model/Contributor.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/model/ProjectBranch.kt
Labels: 2025 / CMP

#430 (FEAT)[#429] 컨트리뷰트 디자인 가이드 적용
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/component/OutlineChipComponent.kt
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/theme/KnightsColor.kt
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/theme/Theme.kt
  feature/contributor/src/main/java/com/droidknights/app/feature/contributor/component/ContributorCardComponent.kt
  feature/contributor/src/main/java/com/droidknights/app/feature/contributor/component/ContributorSectionComponent.kt
  feature/contributor/src/main/java/com/droidknights/app/feature/contributor/component/ContributorTopBannerComponent.kt
  feature/contributor/src/main/res/drawable-hdpi/bg_contributors_darkmode.png
  feature/contributor/src/main/res/drawable-hdpi/bg_contributors_lightmode.png
  feature/contributor/src/main/res/drawable-xhdpi/bg_contributors_darkmode.png
  feature/contributor/src/main/res/drawable-xhdpi/bg_contributors_lightmode.png
  feature/contributor/src/main/res/drawable-xxhdpi/bg_contributors_darkmode.png
  feature/contributor/src/main/res/drawable-xxhdpi/bg_contributors_lightmode.png
  feature/contributor/src/main/res/drawable-xxxhdpi/bg_contributors_darkmode.png
  feature/contributor/src/main/res/drawable-xxxhdpi/bg_contributors_lightmode.png
  feature/contributor/src/main/res/drawable-xxxhdpi/ic_contributor_placeholder_darkmode.png
  feature/contributor/src/main/res/drawable-xxxhdpi/ic_contributor_placeholder_lightmode.png
  feature/contributor/src/main/res/drawable/icon_contributors.xml
  feature/contributor/src/main/res/values/strings.xml
  feature/session/src/main/java/com/droidknights/app/feature/session/detail/component/SessionDetailChip.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/list/component/SessionCard.kt
Labels: 2025

#432 (FEAT)[#431] 네비게이션 디자인 가이드 적용
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/theme/KnightsColor.kt
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/theme/Theme.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/component/MainBottomBar.kt
Labels: enhancement, 2025

#441 [#366] Fix shader issue on Non-Android target
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/ShaderBackground.kt
  feature/home/build.gradle.kts
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSessionCard.kt
Labels: 2025 / CMP

#437 (ENG)[droidknights#438] Network 객체 생성시 명시적 클래스 선언을 inline-reified 로 변경
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/di/ApiModule.kt
  core/data/data-session/src/main/java/com/droidknights/app/core/data/session/di/ApiModule.kt
  core/data/data-sponsor/src/main/java/com/droidknights/app/core/data/sponsor/di/ApiModule.kt
  core/network/network-api/src/main/java/com/droidknights/app/core/network/api/DroidknightsNetwork.kt
  core/network/network/src/test/java/com/droidknights/app/core/network/DroidknightsNetworkImplTest.kt
Labels: 2025

#453 Fix numbering in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 2025

#448 Updates AndroidX May 20, 2025
  gradle/libs.versions.toml
Labels: 2025

#440 [#415] PR 기준으로 빌드된 Desktop App 설치 파일을 다운로드할 수 있는 링크를 코멘트로 달아준다.
  .github/actions/setup-java/action.yml
  .github/workflows/jvm-desktop-build.yml
  .github/workflows/jvm-desktop-comment.yml
  composeApp/build.gradle.kts
  gradle.properties
Labels: 2025 / CMP

#444 ✨오픈 소스 라이센스 메뉴 추가
  composeApp/build.gradle.kts
  core/navigation/src/commonMain/kotlin/com/droidknights/app/core/navigation/RouteModel.kt
  feature/license/.gitignore
  feature/license/build.gradle.kts
  feature/license/src/commonMain/composeResources/files/aboutlibraries.json
  feature/license/src/commonMain/composeResources/values/strings.xml
  feature/license/src/commonMain/kotlin/com/droidknights/app/feature/license/LicenseScreen.kt
  feature/license/src/commonMain/kotlin/com/droidknights/app/feature/license/navigation/LicenseNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainNavigator.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainNavHost.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/SettingScreen.kt
  feature/setting/src/commonMain/kotlin/com/droidknights/app/feature/setting/navigation/SettingNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2025 / CMP
