Repository droidknights/DroidKnightsApp, pull requests merged in 2025-06, with the labels that each got.

#467 [#460] 행사 배치도 카드 배경 Shader 구현 (Layered Radial Gradient 쉐이더 코드 작성)
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/LayeredRadialGradientBackground.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeMapCard.kt
Labels: 2025 / CMP

#477 [#459] 후원 카드 배경 Shader 반영 (EllipticalGlowBackground)
  core/ui/shader/src/commonMain/kotlin/com/droidknights/app/core/shader/components/EllipticalGlowBackground.kt
  feature/home/src/commonMain/composeResources/drawable/background_home_map_card.png
  feature/home/src/commonMain/composeResources/drawable/background_home_session_card.png
  feature/home/src/commonMain/composeResources/drawable/background_home_sponsor_card.png
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSponsorCard.kt
Labels: 2025 / CMP

#488 [#466][CMP] AsyncImage가 Preview에서 안그려지는 문제점을 해결
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Theme.kt
Labels: 2025 / CMP

#492 [#414] Koin Verify Test Code Workflow 작성
  .github/workflows/koin-verify-test.yml
Labels: 2025 / CMP

#498 세션 데이터 최신화
  assets/sessions/sessions.json
  storage/speaker/강다현.jpeg
  storage/speaker/강대규.png
  storage/speaker/강사룡.jpg
  storage/speaker/권대원.png
  storage/speaker/김민구.png
  storage/speaker/김수현.png
  storage/speaker/김주원.jpeg
  storage/speaker/김태성.png
  storage/speaker/김호중.jpeg
  storage/speaker/모진섭.png
  storage/speaker/문종락.png
  storage/speaker/박동후.png
  storage/speaker/박상권.jpeg
  storage/speaker/배필주.png
  storage/speaker/송상윤.jpg
  storage/speaker/신현성.png
  storage/speaker/안성용.jpg
  storage/speaker/양찬석.jpg
  storage/speaker/양찬석.png
  storage/speaker/엄재웅.png
  storage/speaker/옥수환.jpeg
  storage/speaker/윤혁.png
  storage/speaker/윤희성.jpeg
  storage/speaker/이가은.jpg
  storage/speaker/이상훈.png
  storage/speaker/이수호.jpeg
  storage/speaker/이지훈.jpg
  storage/speaker/이현우.png
  storage/speaker/정동진.png
  storage/speaker/차영호.png
  storage/speaker/최우성.png
  storage/speaker/최재웅.png
  storage/speaker/히카맹.png
Labels: 2025, 2025 / CMP

#479 [Feature/#409] Retrofit -> Ktor 마이그레이션 (core:network 구현)
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/com/droidknights/app/App.kt
  core/data/data-session/build.gradle.kts
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/SessionApi.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/SessionRepositoryImpl.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/di/Module.kt
  core/network/build.gradle.kts
  core/network/src/androidMain/kotlin/com/droidknights/app/core/network/engine/HttpClientEngine.kt
  core/network/src/commonMain/kotlin/com/droidknights/app/core/network/DroidKnightsNetwork.kt
  core/network/src/commonMain/kotlin/com/droidknights/app/core/network/di/NetworkModule.kt
  core/network/src/commonMain/kotlin/com/droidknights/app/core/network/engine/HttpClientEngine.kt
  core/network/src/desktopMain/kotlin/com/droidknights/app/core/network/engine/HttpClientEngine.kt
  core/network/src/iosMain/kotlin/com/droidknights/app/core/network/engine/HttpClientEngine.kt
  core/network/src/wasmJsMain/kotlin/com/droidknights/app/core/network/engine/HttpClientEngine.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2025 / CMP

#506 [#505] MockEngine을 이용하여 wasm 환경에서 CORS 문제를 임시적으로 우회
  core/network/build.gradle.kts
  core/network/src/wasmJsMain/kotlin/com/droidknights/app/core/network/HttpClient.kt
  core/network/src/wasmJsMain/kotlin/com/droidknights/app/core/network/mock/Sessions.kt
  gradle/libs.versions.toml
Labels: bug, 2025 / CMP

#510 [CMP] 2025 스폰서 대응
  feature/home/src/commonMain/composeResources/drawable/sponsor_logo_revenue_cat.xml
  feature/home/src/commonMain/composeResources/drawable/svg_sponsor_tier_gold.xml
  feature/home/src/commonMain/composeResources/drawable/svg_sponsor_tier_platinum.xml
  feature/home/src/commonMain/composeResources/values/strings.xml
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSponsorCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/model/Sponsor.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/navigation/HomeNavigation.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainNavigator.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainNavHost.kt
Labels: 2025 / CMP

#516 [CMP] 데스크탑 앱 아이콘 설정
  composeApp/build.gradle.kts
  images/droidknights.icns
  images/droidknights.ico
  images/droidknights.png
  scripts/make_mac_icns.sh
  scripts/make_windows_ico.sh
Labels: enhancement, 2025 / CMP

#497 (FEAT)[#381] Repository에 있는 Fake api 호출 부분 제거
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/api/fake/AssetsDroidnightsContributorsApi.kt
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/di/ApiModule.kt
Labels: 2025

#480 [Feature/#471] 북마크에서 세션 목록으로 리다이렉팅 기능 구현
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/component/Card.kt
  core/designsystem/src/main/java/com/droidknights/app/core/designsystem/theme/KnightsColor.kt
  core/router/router-api/src/main/java/com/droidknights/app/core/router/api/Navigator.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/LaunchedRouter.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/navigator/InternalRoute.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/navigator/NavigatorImpl.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/viewmodel/RouteSideEffect.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/viewmodel/RouterViewModel.kt
  core/router/router/src/test/java/com/droidknights/app/core/router/internal/navigator/NavigatorImplTest.kt
  core/router/router/src/test/java/com/droidknights/app/core/router/internal/viewmodel/RouterViewModelTest.kt
  feature/bookmark/build.gradle.kts
  feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/BookmarkScreen.kt
  feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/BookmarkViewModel.kt
  feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/navigation/BookmarkNavigation.kt
  feature/bookmark/src/test/java/com/droidknights/app/feature/bookmark/BookmarkViewModelTest.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/HomeViewModel.kt
  feature/home/src/test/java/com/droidknights/app/feature/home/HomeViewModelTest.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/component/MainNavHost.kt
  feature/session-api/src/main/java/com/droidknights/app/feature/session/api/RouteSession.kt
  feature/session/build.gradle.kts
  feature/session/src/main/java/com/droidknights/app/feature/session/list/SessionScreen.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/list/component/SessionCard.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/list/model/SessionState.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/navigation/SessionNavigation.kt
Labels: 2025

#524 [#413] 행사 배치도 추가
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/TopAppBar.kt
  core/navigation/src/commonMain/kotlin/com/droidknights/app/core/navigation/RouteModel.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeMapCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/MainNavigator.kt
  feature/main/src/commonMain/kotlin/com/droidknights/app/feature/main/components/MainNavHost.kt
  feature/map/build.gradle.kts
  feature/map/src/commonMain/composeResources/drawable/svg_map_dark_mode.xml
  feature/map/src/commonMain/composeResources/drawable/svg_map_light_mode.xml
  feature/map/src/commonMain/composeResources/values/strings.xml
  feature/map/src/commonMain/kotlin/com/droidknights/app/feature/map/MapScreen.kt
  feature/map/src/commonMain/kotlin/com/droidknights/app/feature/map/components/MapTopAppBar.kt
  feature/map/src/commonMain/kotlin/com/droidknights/app/feature/map/navigation/MapNavigation.kt
  settings.gradle.kts
Labels: 2025 / CMP

#500 [Feature/#493] 2025 스폰서 및 개인 후원자 추가
  core/router/router-api/src/main/java/com/droidknights/app/core/router/api/Navigator.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/LaunchedRouter.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/navigator/InternalRoute.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/navigator/NavigatorImpl.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/viewmodel/RouteSideEffect.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/viewmodel/RouterViewModel.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/component/SponsorCard.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/model/Sponsor.kt
  feature/home/src/main/res/drawable-xxxhdpi/sponsor_logo_koin.png
  feature/home/src/main/res/drawable/sponsor_logo_revenue_cat.xml
  feature/home/src/main/res/drawable/svg_sponsor_tier_gold.xml
  feature/home/src/main/res/drawable/svg_sponsor_tier_platinum.xml
  feature/home/src/main/res/drawable/svg_sponsor_tier_silver.xml
  feature/home/src/main/res/values/strings.xml
Labels: 2025

#520 (FEAT)[#422] Router - 추가 적용
  core/navigation/build.gradle.kts
  core/navigation/src/main/java/com/droidknights/app/core/navigation/MainTabRoute.kt
  core/navigation/src/main/java/com/droidknights/app/core/navigation/RouteModel.kt
  core/router/router-api/src/main/java/com/droidknights/app/core/router/api/Navigator.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/LaunchedRouter.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/navigator/InternalRoute.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/navigator/NavigatorImpl.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/viewmodel/RouteSideEffect.kt
  core/router/router/src/main/java/com/droidknights/app/core/router/internal/viewmodel/RouterViewModel.kt
  core/router/router/src/test/java/com/droidknights/app/core/router/internal/navigator/NavigatorImplTest.kt
  core/router/router/src/test/java/com/droidknights/app/core/router/internal/viewmodel/RouterViewModelTest.kt
  feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/BookmarkScreen.kt
  feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/BookmarkViewModel.kt
  feature/bookmark/src/main/java/com/droidknights/app/feature/bookmark/navigation/BookmarkNavigation.kt
  feature/bookmark/src/test/java/com/droidknights/app/feature/bookmark/BookmarkViewModelTest.kt
  feature/contributor/src/main/java/com/droidknights/app/feature/contributor/navigation/ContributorNavigation.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/HomeScreen.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/droidknights/app/feature/home/navigation/HomeNavigation.kt
  feature/home/src/test/java/com/droidknights/app/feature/home/HomeViewModelTest.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/droidknights/app/feature/main/MainActivity.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/MainScreen.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/MainTab.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/MainViewModel.kt
  feature/main/src/main/java/com/droidknights/app/feature/main/component/MainNavHost.kt
  feature/main/src/test/java/com/droidknights/app/feature/main/MainViewModelTest.kt
  feature/session-api/src/main/java/com/droidknights/app/feature/session/api/RouteSession.kt
  feature/session/build.gradle.kts
  feature/session/src/main/java/com/droidknights/app/feature/session/detail/SessionDetailScreen.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/detail/SessionDetailViewModel.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/list/SessionListViewModel.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/list/SessionScreen.kt
  feature/session/src/main/java/com/droidknights/app/feature/session/navigation/SessionNavigation.kt
  feature/session/src/test/java/com/droidknights/app/feature/session/detail/SessionDetailViewModelTest.kt
  feature/session/src/test/java/com/droidknights/app/feature/session/list/SessionListViewModelTest.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/droidknights/app/feature/setting/SettingScreen.kt
  feature/setting/src/main/java/com/droidknights/app/feature/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/droidknights/app/feature/setting/navigation/SettingNavigation.kt
  feature/setting/src/test/java/com/droidknights/app/feature/setting/SettingViewModelTest.kt
Labels: 2025

#519 [Feature/#419]: Compose Multiplatform Preview Screenshot Test 적용
  .github/workflows/screenshot-comparison.yml
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/com/droidknights/app/Extensions.kt
  build-logic/src/main/kotlin/com/droidknights/app/convention/DroidKnightsFeaturePlugin.kt
  build-logic/src/main/kotlin/com/droidknights/app/primitive/ComposeGradleDsl.kt
  build-logic/src/main/kotlin/com/droidknights/app/primitive/KotlinMultiPlatformRoborazziPlugin.kt
  build.gradle.kts
  core/designsystem/build.gradle.kts
  core/designsystem/screenshot/ChipPreview.png
  core/designsystem/screenshot/KnightsTopAppBarPreviewBack.png
  core/designsystem/screenshot/KnightsTopAppBarPreviewClose.png
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/components/Chip.kt
  core/testing/build.gradle.kts
  core/testing/src/androidMain/kotlin/com/droidknights/app/core/testing/DroidKnightKmpPreviewTester.kt
  core/testing/src/androidMain/kotlin/com/droidknights/app/core/testing/ProvideAndroidContextToComposeResource.kt
  feature/home/screenshot/HomeContributorCardPreview.png
  feature/home/screenshot/HomeMapCardPreview.png
  feature/home/screenshot/HomeScreenPreview.png
  feature/home/screenshot/HomeSessionCardPreview.png
  feature/home/screenshot/HomeSponsorCardDarkPreview.png
  feature/home/screenshot/HomeSponsorCardLightPreview.png
  feature/main/screenshot/MainBottomBarPreview.png
  feature/session/screenshot/SessionCardPreview.png
  feature/session/screenshot/SessionDetailScreenPreview.png
  feature/session/screenshot/TagChipPreview.png
  feature/session/screenshot/TimeChipPreview.png
  feature/session/screenshot/TrackChipPreview.png
  feature/setting/screenshot/SettingDarkThemeCardPreview.png
  feature/setting/screenshot/SettingOpenSourceCardPreview.png
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 2025 / CMP

#523 [#511] Bookmark 페이지 추가
  composeApp/build.gradle.kts
  composeApp/src/commonMain/kotlin/com/droidknights/app/App.kt
  core/designsystem/src/commonMain/kotlin/com/droidknights/app/core/designsystem/theme/Color.kt
  core/domain/domain-session/src/commonMain/kotlin/com/droidknights/app/core/domain/session/usecase/GetBookmarkedSessionsUseCaseImpl.kt
  feature/bookmark/build.gradle.kts
  feature/bookmark/src/androidMain/kotlin/com/droidknights/app/feature/bookmark/component/BackHandler.android.kt
  feature/bookmark/src/commonMain/composeResources/drawable/ic_check.xml
  feature/bookmark/src/commonMain/composeResources/drawable/ic_menu.xml
  feature/bookmark/src/commonMain/composeResources/drawable/ic_trash.xml
  feature/bookmark/src/commonMain/composeResources/values/strings.xml
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/BookmarkScreen.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/BookmarkViewModel.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/BackHandler.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/BookmarkCard.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/BookmarkItem.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/BookmarkTimeline.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/BookmarkTopAppBar.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/EditModeLeadingItem.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/component/RemoveBookmarkSnackBar.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/di/Module.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/model/BookmarkItemUiState.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/model/BookmarkUiState.kt
  feature/bookmark/src/commonMain/kotlin/com/droidknights/app/feature/bookmark/navigation/BookmarkNavigation.kt
  feature/bookmark/src/nonAndroidMain/kotlin/com/droidknights/app/feature/bookmark/component/BackHandler.nonAndroid.kt
Labels: 2025 / CMP

#531 (FEAT)[#481] 메이커 정보 최신화
  app-config/app-config/src/main/java/com/droidknights/app/config/DroidknightsBuildConfigImpl.kt
  assets/contributors.json
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/ContributorRepositoryImpl.kt
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/api/GithubContributorsApi.kt
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/di/ApiModule.kt
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/mapper/ContributorMapper.kt
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/model/ContributionYearResponse.kt
  core/data/data-contributor/src/main/java/com/droidknights/app/core/data/contributor/model/ContributorResponse.kt
  core/data/data-contributor/src/test/assets/contributors.json
  core/data/data-contributor/src/test/java/com/droidknights/app/core/data/contributor/ContributorRepositoryImplTest.kt
  core/data/data-contributor/src/test/java/com/droidknights/app/core/data/contributor/api/fake/FakeGithubContributorsApi.kt
  core/domain/domain-contributor/src/test/java/com/droidknights/app/core/domain/contributor/usecase/GetContributorsUseCaseImplTest.kt
  core/model/model-contributor/src/main/java/com/droidknights/app/core/model/contributor/Contributor.kt
  feature/contributor/src/test/java/com/droidknights/app/feature/contributor/ContributorViewModelTest.kt
Labels: 2025

#529 [CMP] 라이브러리 버전 업데이트
  .github/workflows/screenshot-comparison.yml
  gradle/libs.versions.toml
Labels: 2025 / CMP

#533 (FEAT)[#481] cmp 메이커 정보 갱신
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/ContributorRepositoryImpl.kt
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/api/DroidknightsContributorsApi.kt
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/api/GithubContributorsApi.kt
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/di/Module.kt
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/mapper/ContributorMapper.kt
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/model/ContributionYearResponse.kt
  core/data/data-contributor/src/commonMain/kotlin/com/droidknights/app/core/data/contributor/model/ContributorResponse.kt
  core/data/data-session/src/commonMain/kotlin/com/droidknights/app/core/data/session/SessionApi.kt
  core/model/model-contributor/src/commonMain/kotlin/com/droidknights/app/core/model/contributor/Contributor.kt
  core/network/src/wasmJsMain/kotlin/com/droidknights/app/core/network/mock/Sessions.kt
Labels: 2025 / CMP

#537 [CMP] Koin 스폰서 및 개인 후원자 추가
  feature/bookmark/screenshot/BookmarkCardDarkPreview.png
  feature/bookmark/screenshot/BookmarkCardLightPreview.png
  feature/bookmark/screenshot/BookmarkItemPreview.png
  feature/bookmark/screenshot/BookmarkScreenDarkPreview.png
  feature/bookmark/screenshot/BookmarkScreenLightPreview.png
  feature/bookmark/screenshot/BookmarkStatePopupPreview.png
  feature/bookmark/screenshot/BookmarkTimelineItemDarkPreview.png
  feature/bookmark/screenshot/BookmarkTimelineItemLightPreview.png
  feature/bookmark/screenshot/BookmarkTopAppBarDarkPreview.png
  feature/bookmark/screenshot/BookmarkTopAppBarEditModeDarkPreview.png
  feature/bookmark/screenshot/BookmarkTopAppBarEditModeLightPreview.png
  feature/bookmark/screenshot/BookmarkTopAppBarLightPreview.png
  feature/bookmark/screenshot/CheckedEditModeLeadingItemPreview.png
  feature/bookmark/screenshot/UncheckedEditModeLeadingItemPreview.png
  feature/home/screenshot/HomeScreenPreview.png
  feature/home/screenshot/HomeSponsorCardDarkPreview.png
  feature/home/screenshot/HomeSponsorCardLightPreview.png
  feature/home/src/commonMain/composeResources/drawable/sponsor_logo_koin.png
  feature/home/src/commonMain/composeResources/drawable/svg_sponsor_tier_silver.xml
  feature/home/src/commonMain/composeResources/values/strings.xml
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/components/HomeSponsorCard.kt
  feature/home/src/commonMain/kotlin/com/droidknights/app/feature/home/model/Sponsor.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/DeviceFrame.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/components/ProjectDescription.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/model/Contributor.kt
  feature/main/src/wasmJsMain/kotlin/com/droidknights/app/feature/main/model/Sponsor.kt
Labels: 2025 / CMP

#544 Feature[#543]: screenshot-comparison.yml 워크플로우 수정
  .github/workflows/screenshot-comparison.yml
  feature/home/screenshot/HomeScreenPreview.png
  feature/home/screenshot/HomeSponsorCardDarkPreview.png
  feature/home/screenshot/HomeSponsorCardLightPreview.png
Labels: 2025 / CMP
